profile=high-quality
vo=gpu-next  # Uses modern GPU renderer.

gpu-api=vulkan  # Forces Vulkan backend
#fullscreen=yes  # start fullscreen
force-seekable=yes  # better for broken files bad for live streams
keep-open=always  # mpv stays open even when video ends, playlist won't auto advance

reset-on-next-file=pause
hwdec=safe
scale-antiring=0.6

scale=ewa_lanczos
dscale=mitchell
#cscale=ewa_lanczossharp
cscale=bilinear


# ==========    DEBANDING    ==========
# Banding is a visual artifact, visual artifacts should never be in a video. 
# Debanding is the process of removing said banding.

deband=no
deband-iterations=2
deband-threshold=48
deband-range=17
deband-grain=12


# ==========    ON SCREEN DISPLAY AND ON SCREEN CONTROLLER    ==========

osd-bar=no
border=no
cursor-autohide-fs-only=yes
cursor-autohide=1000
osd-level=1
osd-duration=1000
hr-seek=yes

osd-font='Verdana'
osd-font-size=20
osd-color='#FFFFFF'
osd-border-color='#000000'
osd-border-size=0.6
osd-blur=0.2


# ==========    LANGUAGE PRIORITY    ==========
alang=ja,jp,jpn,en,eng
slang=en,eng


# ==========    AUDIO    ==========
volume=100
audio-file-auto=fuzzy
volume-max=200
audio-pitch-correction=yes


# ==========    SUBTITLES    ==========
demuxer-mkv-subtitle-preroll=yes
sub-fix-timing=no
sub-auto=fuzzy

# The following options only apply to subtitles without own styling
#sub-font='Inter'
#sub-font-size=40
#sub-color='#FFFFFFFF'
#sub-border-color='#FF000000'
#sub-border-size=2.0
#sub-shadow-color="#A0000000"
#sub-shadow-offset=0.75
#sub-spacing=0.0
#sub-bold=yes


# ==========    SCREENSHOT    ==========
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=4
screenshot-directory="~/Downloads"
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"


# ==========    AUTO PROFILES    ==========

# Auto profile that automatically applies for WEB-DL anime that need some debanding
[WEB-DL]
    profile-desc=WEB-DL Anime (HatSubs, SubsPlease, HorribleSubs, Erai-raws)
    profile-cond=string.match(p.filename, "HatSubs")~=nil or string.match(p.filename, "SubsPlease")~=nil or string.match(p.filename, "HorribleSubs")~=nil or string.match(p.filename, "Erai%-raws")~=nil
    deband=yes
