[ids]
# empty = apply to ALL keyboards
*

[main]
#dot = backspace
#backspace = dot
#shift+backspace = >
#
#capslock = leftmeta
#esc = slash
#shift+esc = ?
#
#leftmeta = esc
#slash = backspace

#semicolon = leftmeta
#capslock = backspace
#
esc = middlemouse
#backspace = semicolon
#shift+backspace = colon 

f10 = capslock

#capslock = leftmeta
#leftmeta = esc
#comma = backspace
#dot = backspace
#backspace = dot
#shift+backspace = >
#shift+esc = ?
#esc = slash
#slash = comma
#shift+slash = <

capslock = leftmeta
leftmeta = esc
dot = backspace
#comma = backspace
#dot = comma
#shift+dot = <
backspace = dot
shift+backspace = >
